services:
  micro-empregados:
    build: .
    image: taohans/gestaocerta:micro-empregados
    container_name: micro-empregados
    environment:
      - APP_PROFILE=dev
      - SERVER_PORT=8081
      - DB_HOST=postgres-db-emp
      - DB_PORT=5432
      - DB_NAME=microservice_db
      - DB_USER=postgres
      - DB_PASS=postgres
      - GATEWAY_URL=http://localhost:8080/emp/
      - RABBITMQ_HOST=rabbitmq-server
      - RABBITMQ_USER=rabbitmq
      - RABBITMQ_PASS=rabbitmq
    networks:
      - gestaocerta-private
      - int-empregados-net

  postgres-db-emp:
    image: postgres:15
    container_name: postgres-db-emp
    environment:
      POSTGRES_DB: microservice_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - int-empregados-net
    volumes:
      - postgres_data_emp:/var/lib/postgresql/data

networks:
  gestaocerta-private:
    external: true
  int-empregados-net:

volumes:
  postgres_data_emp:
    driver: local
